model_architecture = "multi_res_bi_gru"
#exp_name = "0.8-nan-12-interval"
exp_name = "0.8-nan-12-interval-patient-10"
#exp_name = "0.8-nan-12-interval-patient-10_4"

[model]
hidden_size = 64
out_size = 2
n_layers = 5

max_chunk_size = 500_000

[dataset]
sigma = 108
agg_interval = 12  # 5sec/pt
#agg_interval = 3  # 5sec/pt
features = [
    "max",
    "min",
    "mean",
    "std",
    "median",
#    "q25",
#    "q75"
#    "fft",
]
#train_dataset_type = "base"
train_dataset_type = "with_part_id"

[train]
#num_epochs = 20
num_epochs = 30
train_batch_size = 1
valid_batch_size = 1
learning_rate = 0.001

#lower_nan_fraction_to_exclude = 0.8
lower_nan_fraction_to_exclude = -1

fold_type = "group"
#fold_type = "stratified_group"
n_folds = 5

#early_stopping_patience = 5
early_stopping_patience = 10
#early_stopping_max_epoch = 20

save_top_k_models = 3

[train.optimizer]
weight_decay = 0

[train.optimizer.scheduler]
eta_min = 2e-8

[eval]
window = 40  # minutes on half side

